### ISSUE TITLE
Naming of folders

### ISSUE THREAD

**Issue by niiadoteibrown** [niiadoteibrown/sarpong#3]
Naming of folders should follow common coding practices and standards. Folders should have a **short name**. The names of folders should either be all **lowercase**, **snake case** or **camel case**. 

For example: 
Alfred_Appiagyei should be alfred_appiagyei, alfredAppiagyei or alfredappiagyei

**Comment by kevin2-cyber** [comment]
Please what about hyphenated?

**Comment by niiadoteibrown** [comment]
no hypens too
