### ISSUE TITLE
Requesting Access to Repository

### ISSUE THREAD

**Issue by nadjeley** [niiadoteibrown/sarpong#55]

**Comment by niiadoteibrown** [comment]
Your mail?

**Comment by nadjeley** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by nadjeley** [comment]
Please no invitation has been sent yet to my email. I have  checked my spam email as you told me to but nothing has been sent. 
Please my email is : itsalexisaddo@gmail.com
